Repository alejandroluisacosta/devathon-8-frontend, pull requests merged in 2024-11, with the labels that each got.

#2 docs: update README.md
  README.md
Labels: documentation

#5 add: Template
  package.json
  src/App.css
  src/App.tsx
  src/components/index.ts
  src/components/ui/sidebar/SideBar.tsx
  src/components/ui/sidebar/sideBar.scss
  src/constants/routes.tsx
  src/index.css
  src/index.scss
  src/main.tsx
  src/pages/calories/CaloriesPage.tsx
  src/pages/chill/ChillPage.tsx
  src/pages/elves/ElvesPage.tsx
  src/pages/gps/GpsPage.tsx
  src/pages/gps/gps.scss
  src/pages/grades/GradesPage.tsx
  src/pages/index.ts
  src/pages/reader/ReaderPage.tsx
  src/pages/reindeers/ReindeersPage.tsx
  src/styles/reset/_reset.scss
  src/template/DashboardTemplate.tsx
  src/template/dasboardTemplate.scss
Labels: enhancement

#6 feat: add map preview
  .env.example
  index.html
  package.json
  src/main.tsx
  src/pages/gps/GpsPage.tsx
  src/pages/gps/gps.scss
Labels: enhancement

#12 Update/gps
  public/images/grinch.webp
  src/App.tsx
  src/api/directionsApi.ts
  src/api/index.ts
  src/api/searchApi.ts
  src/components/gps/grinch-marker/GrinchMarker.tsx
  src/components/gps/map-preview/MapPreview.tsx
  src/components/gps/search-bar/SearchBar.tsx
  src/components/gps/search-bar/searchBar.scss
  src/components/gps/search-results/SearchResults.tsx
  src/components/gps/search-results/searchResults.scss
  src/components/index.ts
  src/components/ui/map-skeleton/MapSkeleton.tsx
  src/components/ui/map-skeleton/mapSkeleton.scss
  src/components/ui/search-results-skleton/SearchResultsSkeleton.tsx
  src/components/ui/search-results-skleton/searchResultsSkeleton.scss
  src/context/index.ts
  src/context/map/MapContext.ts
  src/context/map/MapProvider.tsx
  src/context/map/mapReducer.ts
  src/context/places/PlacesContext.ts
  src/context/places/PlacesProvider.tsx
  src/context/places/placesReducer.ts
  src/hook/index.ts
  src/hook/useMap.ts
  src/hook/usePlaces.ts
  src/interfaces/PlacesResponce.interface.ts
  src/interfaces/directions.interface.ts
  src/main.tsx
  src/pages/gps/GpsPage.tsx
  src/utils/addRouteToMap.ts
  src/utils/getUserLocation.ts
  src/utils/grinchMarker.ts
  src/utils/index.ts
  src/utils/mapUtils.ts
Labels: bug, enhancement

#11 Feature/registry searches
  src/components/history/History.scss
  src/components/history/History.tsx
  src/components/search/Search.scss
  src/components/search/Search.tsx
  src/pages/index.ts
Labels: enhancement

#14 Feature/registry searches
  src/components/history/History.scss
  src/components/history/History.tsx
  src/components/search-save/SearchSave.scss
  src/components/search-save/SearchSave.tsx
  src/interfaces/history.interface.ts
  src/pages/gps/GpsPage.tsx
Labels: enhancement

#17 Implement update updateHistory to save histories entries
  src/api/fetchAPIBackend.ts
  src/api/index.ts
  src/components/gps/search-results/SearchResults.tsx
  src/context/history/HistoryProvider.tsx
  src/context/history/historyReducer.ts
  src/interfaces/history.interface.ts
  src/utils/index.ts
  src/utils/isInHistory.ts
Labels: enhancement

#19 fix: styles history container
  src/components/history/History.scss
Labels: bug

#20 fix: add webpage name and icon in the navbar
  index.html
  public/images/gift.svg
Labels: bug

#22 feature: letter-modal component
  src/components/letter-modal/LetterModal.scss
  src/components/letter-modal/LetterModal.tsx
  src/interfaces/letter.interface.ts
Labels: enhancement

#24 feat: fix history to show only five results in the history
  src/context/history/historyReducer.ts
Labels: bug

#25 fix: favicon link console error message
  index.html
Labels: bug

#26 fix: letter stamp position and text
  src/components/letter-modal/LetterModal.scss
  src/components/letter-modal/LetterModal.tsx
Labels: bug

#29 Letters/table
  src/components/pagination/Pagination.tsx
  src/pages/reader/ReaderPage.tsx
  src/utils/index.ts
  src/utils/parseQuery.ts
Labels: enhancement

#30 fix: logic of letter stamp
  src/components/letter-modal/LetterModal.tsx
Labels: bug

#32 Fix/letter status
  src/components/reader/reader-table/ReaderTable.tsx
  src/components/reader/reader-table/readerTable.scss
  src/components/reader/reader-table/readt-status/readStatus.scss
  src/components/ui/sidebar/sideBar.scss
  src/index.scss
  src/template/DashboardTemplate.tsx
  src/template/dasboardTemplate.scss
Labels: bug, enhancement

#33 fix: fix GPS title responsive
  src/pages/gps/gps.scss
  src/styles/reset/_reset.scss
Labels: bug

#34 Docs/update readme
  .env.example
  README.md
Labels: documentation

#36 feature: add skeleton history
  src/components/history/History.tsx
  src/components/ui/history-skeleton/HistorySkeleton.scss
  src/components/ui/history-skeleton/HistorySkeleton.tsx
  src/context/history/HistoryProvider.tsx
Labels: enhancement
